#!/bin/sh
# p01nt <p01nt@klets.name>

name=`basename $0`
title=`echo ${name} | awk -F_ '{print $NF}'`

hp_stat() {
	echo "show stat" | socat unix-connect:/tmp/haproxy stdio
}

servers_section() {
	hp_stat | grep '^'${title}',' |  egrep -v '^'${title}',(FRONTEND|BACKEND)'
}

servers() {
	servers_section | awk -F, '{print $2}'
}

labels() {
	cat <<EOF
req.label requests
conn.label connections
resp.label responses
EOF
}

values() {
	cat <<EOF
req.value `hp_stat | grep '^'${title}',FRONTEND' | awk -F, '{print $13}'`
conn.value `hp_stat | grep '^'${title}',BACKEND' | awk -F, '{print $14}'`
resp.value `hp_stat | grep '^'${title}',BACKEND' | awk -F, '{print $15}'`
EOF
}


case $1 in
   config)
		cat <<EOF
graph_title ${title} errors
graph_vlabel ${name}
graph_category haproxy

`labels`
EOF
		exit 0
	;;
esac

values
