#!/bin/sh
# p01nt <p01nt@klets.name>

name=`basename $0`
title=`echo ${name} | awk -F_ '{print $NF}'`

hp_stat() {
	echo "show stat" | socat unix-connect:/tmp/haproxy stdio
}

servers_section() {
	hp_stat | grep '^'${title}',' |  egrep -v '^'${title}',(FRONTEND|BACKEND)'
}

servers() {
	servers_section | awk -F, '{print $2}'
}

labels() {
	servers_section | awk -F, '{print $2".label "$2}'
}

values() {
	servers_section | awk -F, '{print $2".value "$22}'
}


case $1 in
   config)
		cat <<EOF
graph_title ${title} failed checks
graph_vlabel ${name}
graph_category haproxy

`labels`
EOF
		exit 0
	;;
esac

values
